version: '3'
services:
  db:
    image: postgres:15-alpine
    volumes:
      - ./db_data:/var/lib/postgresql/data
    env_file:
      - .env.example
    expose:
      - 5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
  ingest:
    build: .
    command: [ "python3","src/run.py", "--folder_path=data"]
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env.example
    volumes:
      - ./ingest/:/mnt/
  web:
    build: .
    command: >
      sh -c "python manage.py migrate &&
             python manage.py createsuperuser --noinput ||
             python manage.py runserver 0.0.0.0:8000"
    ports:
      - "80:8000"
    depends_on:
      - ingest
      - db
    env_file:
      - .env.example
    volumes:
      - ./web/:/mnt/






